#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

fineract.tenants['default'].tenant-identifier=default
fineract.tenants['default'].name=fineract_default
fineract.tenants['default'].timezone-id=Asia/Kolkata
fineract.tenants['default'].description=Default Demo Tenant
fineract.tenants['default'].connection.schema-protocol=mariadb
fineract.tenants['default'].connection.schema-server=localhost
fineract.tenants['default'].connection.schema-server-port=3306
fineract.tenants['default'].connection.schema-connection-parameters=
fineract.tenants['default'].connection.schema-username=root
fineract.tenants['default'].connection.schema-password=mysql
fineract.tenants['default'].connection.schema-name=
fineract.tenants['default'].connection.read-only-schema-protocol=${FINERACT_RO_SCHEMA_SERVER_NAME:mariadb}
fineract.tenants['default'].connection.read-only-schema-server=${FINERACT_RO_SCHEMA_SERVER_NAME:localhost}
fineract.tenants['default'].connection.read-only-schema-server-port=${FINERACT_RO_SCHEMA_SERVER_PORT:3306}
fineract.tenants['default'].connection.read-only-schema-name=${FINERACT_RO_SCHEMA_SCHEMA_NAME:}
fineract.tenants['default'].connection.read-only-schema-username=${FINERACT_RO_SCHEMA_USERNAME:root}
fineract.tenants['default'].connection.read-only-schema-password=${FINERACT_RO_SCHEMA_PASSWORD:mysql}
fineract.tenants['default'].connection.read-only-schema-connection-parameters=${FINERACT_RO_SCHEMA_CONNECTION_PARAMETERS:}
fineract.tenants['default'].connection.auto-update-enabled=true
fineract.tenants['default'].connection.initial-size=5
fineract.tenants['default'].connection.validation-interval=30000
fineract.tenants['default'].connection.remove-abandoned=true
fineract.tenants['default'].connection.remove-abandoned-timeout=60
fineract.tenants['default'].connection.log-abandoned=true
fineract.tenants['default'].connection.abandon-when-percentage-full=50
fineract.tenants['default'].connection.max-active=40
fineract.tenants['default'].connection.min-idle=20
fineract.tenants['default'].connection.max-idle=10
fineract.tenants['default'].connection.suspect-timeout=60
fineract.tenants['default'].connection.time-between-eviction-runs-millis=34000
fineract.tenants['default'].connection.min-evictable-idle-time-millis=60000
fineract.tenants['default'].connection.test-on-borrow=false
