/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

dependencies {
    compileOnly(
            'org.springframework.boot:spring-boot-autoconfigure',
            'org.eclipse.persistence:org.eclipse.persistence.jpa'
            )
    implementation(
            project(':fineract-core'),
            project(':fineract-provider'),
            project(':custom:apachecon:command:core'),
            project(':custom:apachecon:command:data'),
            project(':custom:apachecon:command:mapping'),
            'org.springframework.data:spring-data-commons',
            'org.apache.camel.springboot:camel-spring-boot-starter',
            'org.apache.camel.springboot:camel-spring-starter',
            'org.apache.camel.springboot:camel-spring-security-starter',
            'org.apache.camel.springboot:camel-language-starter',
            'org.apache.camel.springboot:camel-direct-starter',
            'org.apache.camel.springboot:camel-disruptor-starter',
            'org.apache.camel.springboot:camel-jgroups-starter',
            'org.apache.camel.springboot:camel-nats-starter',
            'org.apache.camel.springboot:camel-jackson-starter',
            'org.apache.httpcomponents:httpcore',
            'jakarta.servlet:jakarta.servlet-api',
            )
}
