/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
description = 'Fineract Module: Eclipse BIRT Service'

apply plugin: 'java'
apply plugin: 'eclipse'

apply from: 'dependencies.gradle'

repositories {
    flatDir {
        dirs layout.buildDirectory.dir('libs')
    }
}

task downloadFile(type: Download) {
    src 'https://ftp2.osuosl.org/pub/eclipse/birt/updates/release/4.14.0/downloads/birt-runtime-4.14.0-202312020807.zip'
    dest layout.buildDirectory
    onlyIfModified true
}

task unpack(type: Copy) {
    from layout.buildDirectory
    into layout.buildDirectory.dir('tmp')
    filesMatching '*.zip', { zipDetails ->
        copy {
            from zipTree(zipDetails.file)
            into destinationDir
        }
        zipDetails.exclude()
    }
}