name: Sync Upstream Fineract

env:
  UPSTREAM_URL: "https://github.com/apache/fineract.git"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# This runs every hour
on:
  schedule:
    - cron: '0 * * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Sync
        run:  |
          set -ex;
          git config --local user.email "vidakovic@users.noreply.github.com";
          git config --local user.name  "Aleksandar Vidakovic";
          git remote add upstream "https://github.com/apache/fineract.git";
          git fetch upstream;
          git checkout develop;
          git rebase upstream/develop;
          git push origin develop;
